//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_gastos
    {
        public string codigo_rubro { get; set; }
        public string tipo_rubro { get; set; }
        public string etiqueta_rubro { get; set; }
        public string rubro { get; set; }
        public string cod { get; set; }
        public string desc_gast { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string filtro { get; set; }
    }
}
