//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_rmeses
    {
        public System.Guid id_rubro { get; set; }
        public string tipo_rubro { get; set; }
        public string etiqueta_rubro { get; set; }
        public string rubro { get; set; }
        public Nullable<decimal> monto_fijo { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<decimal> montof { get; set; }
    }
}
