//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact_areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fact_areas()
        {
            this.inf_usuarios = new HashSet<inf_usuarios>();
        }
    
        public System.Guid id_area { get; set; }
        public string cod_area { get; set; }
        public Nullable<int> id_est_areas { get; set; }
        public string desc_areas { get; set; }
        public System.Guid id_emp { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual fact_est_areas fact_est_areas { get; set; }
        public virtual inf_emp inf_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_usuarios> inf_usuarios { get; set; }
    }
}
