//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_control_montos
    {
        public System.Guid id_control_monto { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_rubro { get; set; }
    
        public virtual inf_rubro inf_rubro { get; set; }
    }
}
