//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_rubro_mes
    {
        public System.Guid id_rubro_mes { get; set; }
        public Nullable<int> id_est_rubm { get; set; }
        public Nullable<decimal> monto_fijo { get; set; }
        public Nullable<int> minimo { get; set; }
        public Nullable<int> min { get; set; }
        public Nullable<int> maximo { get; set; }
        public Nullable<int> max { get; set; }
        public Nullable<decimal> monto_extra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_rubro { get; set; }
    
        public virtual fact_est_rubm fact_est_rubm { get; set; }
        public virtual inf_rubro inf_rubro { get; set; }
    }
}
