//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_conc_ec
    {
        public System.Guid id_conc_ec { get; set; }
        public string dia_ensaye { get; set; }
        public Nullable<int> num_muesra { get; set; }
        public Nullable<System.DateTime> fecha_ensaye { get; set; }
        public int id_est_ensaye { get; set; }
        public Nullable<int> cde { get; set; }
        public Nullable<int> cdem { get; set; }
        public Nullable<int> clave_ensa_a { get; set; }
        public Nullable<decimal> masa_a { get; set; }
        public Nullable<decimal> altura_a { get; set; }
        public Nullable<decimal> altura_b { get; set; }
        public Nullable<decimal> lados_a { get; set; }
        public Nullable<decimal> lados_b { get; set; }
        public Nullable<int> directo_a { get; set; }
        public string intensidad_a { get; set; }
        public Nullable<decimal> presion_a { get; set; }
        public string tipofalla_a { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_mrp_concreto { get; set; }
    
        public virtual fact_est_ensaye fact_est_ensaye { get; set; }
        public virtual inf_mrp_concreto inf_mrp_concreto { get; set; }
    }
}
