//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_caja
    {
        public System.Guid id_caja { get; set; }
        public Nullable<int> id_est_caja { get; set; }
        public Nullable<int> id_estatus_rpt { get; set; }
        public Nullable<int> id_tipo_rubro { get; set; }
        public System.Guid id_rubro { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_emp { get; set; }
        public string desc_caja { get; set; }
        public string codigo_caja { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_est_caja fact_est_caja { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
