//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_gastos_dep
    {
        public int id_gastos_dep { get; set; }
        public int id_tipo_rubro { get; set; }
        public System.Guid id_rubro { get; set; }
        public Nullable<int> id_estatus_montos { get; set; }
        public System.Guid id_gasto { get; set; }
    
        public virtual inf_gastos inf_gastos { get; set; }
    }
}
