//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_seg_prospecto
    {
        public System.Guid id_seg_prospecto { get; set; }
        public Nullable<int> id_tipo_accion { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_usuario { get; set; }
        public System.Guid id_prospecto { get; set; }
    }
}
