//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_email_recepcion
    {
        public System.Guid id_email_recep { get; set; }
        public Nullable<int> id_est_e_recep { get; set; }
        public string email_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_emp { get; set; }
    
        public virtual fact_est_e_recep fact_est_e_recep { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
