//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_cont_usr
    {
        public int id_dir_usuario { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public string telefono { get; set; }
        public string movil { get; set; }
        public string email { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
