//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_email_envio
    {
        public System.Guid id_email_env { get; set; }
        public Nullable<int> id_est_e_env { get; set; }
        public string email { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string asunto { get; set; }
        public string servidor_smtp { get; set; }
        public Nullable<int> puerto { get; set; }
        public System.Guid id_emp { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual fact_est_e_env fact_est_e_env { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
