//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ensa_comp
    {
        public string no_muesra { get; set; }
        public Nullable<System.DateTime> fecha_colado { get; set; }
        public Nullable<int> presion { get; set; }
        public int id_tipo_especimen { get; set; }
        public int id_tipo_concreto { get; set; }
        public int id_sit_concreto { get; set; }
        public string fa1 { get; set; }
        public string fa3 { get; set; }
        public string fa7 { get; set; }
        public string fa14 { get; set; }
        public string fa28 { get; set; }
        public string fao { get; set; }
        public Nullable<int> ne1 { get; set; }
        public Nullable<int> ne3 { get; set; }
        public Nullable<int> ne7 { get; set; }
        public Nullable<int> ne14 { get; set; }
        public Nullable<int> ne28 { get; set; }
        public Nullable<int> neo { get; set; }
        public Nullable<System.DateTime> f_ensa_comp { get; set; }
        public int fpfe { get; set; }
        public Nullable<int> fne { get; set; }
    }
}
