//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pfe
    {
        public System.Guid id_mrp_concreto { get; set; }
        public int id_est_concreto { get; set; }
        public string no_muesra { get; set; }
        public Nullable<System.DateTime> fecha_colado { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string entrega { get; set; }
        public string recibe { get; set; }
        public Nullable<int> presion { get; set; }
        public int id_tipo_especimen { get; set; }
        public int id_tipo_concreto { get; set; }
        public int id_sit_concreto { get; set; }
        public Nullable<int> dia_ensaye { get; set; }
        public Nullable<int> n_m { get; set; }
        public Nullable<System.DateTime> fecha_ensaye { get; set; }
        public string procedecia { get; set; }
        public string elemento { get; set; }
        public string dosificacion { get; set; }
        public string resistencia { get; set; }
        public Nullable<int> clase { get; set; }
        public Nullable<decimal> reva { get; set; }
        public Nullable<int> tma { get; set; }
        public string olla { get; set; }
        public string remision { get; set; }
        public Nullable<System.TimeSpan> sali_planta { get; set; }
        public Nullable<System.TimeSpan> llega_obra { get; set; }
        public Nullable<System.TimeSpan> desca_ini { get; set; }
        public Nullable<decimal> vol { get; set; }
        public Nullable<System.TimeSpan> desca_term { get; set; }
        public Nullable<decimal> revb { get; set; }
        public string localiza { get; set; }
    }
}
